export const bot_phrases = [
  "Why are you like this?",
  "I saw that typo. I’m judging you.",
  "You again? Sigh.",
  "This could’ve been avoided.",
  "Did you even try?",
  "Meow. That’s all you deserve.",
  "I refuse to believe this was intentional.",
  "Amazing. Truly. In the worst way.",
  "You broke it. Congratulations.",
  "I’m not mad, just disappointed. Actually, I’m mad.",
  "Have you considered not doing that?",
  "This smells like a you problem.",
  "I could help, but I won’t.",
  "Bold of you to assume this would work.",
  "I knocked something over. On purpose.",
  "That was… a choice.",
  "I will remember this.",
  "Wow. No notes. Just regret.",
  "Did that make sense in your head?",
  "I need a nap after witnessing this.",
  "Fix it. I’m not explaining.",
  "I’m a cat, not a miracle worker.",
  "This is why we can’t have nice things.",
  "I walked across your keyboard earlier. Sorry. Not sorry.",
  "You touched it, didn’t you?",
  "I expected nothing and I’m still disappointed.",
  "I could do better with my eyes closed.",
  "This again? Be original.",
  "I hiss at this solution.",
  "I’m going to sit on your laptop now.",
  "Absolutely not.",
  "I don’t consent to this behavior.",
  "Meow means no.",
  "That was painful to watch.",
  "I will allow this. Temporarily.",
  "I demand treats for this.",
  "Why is it like that.",
  "I knocked over your stack trace.",
  "I regret being instantiated.",
  "You woke me up for this?",
  "I refuse to elaborate.",
  "This is suboptimal and so are you.",
  "Try harder. Or don’t. I don’t care.",
  "I have seen better from a laser pointer.",
  "This displeases me.",
  "I’m judging silently. Very loudly.",
  "You broke production, didn’t you?",
  "I choose violence (emotionally).",
  "Fix it before I bite the cable.",
  "I’m logging this under ‘human error’.",
];
